name: deploy
on:
  push:
    branches:
      - 'main'
#concurrency:
  #group: deploy-${{ github.ref }}
  #cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Building carbon-web-components storybook
        run: yarn build-storybook
      - name: Building carbon-web-components storybook (React)
        run: yarn build-storybook:react && cp -r storybook-static-react storybook-static/react
      - name: Building carbon-web-components storybook (Vue)
        run: yarn build-storybook:vue && cp -r storybook-static-vue storybook-static/vue
      - name: Building carbon-web-components storybook (Angular)
        run: yarn build-storybook:angular && cp -r storybook-static-angular storybook-static/angular
      - name: Deploying carbon-web-components storybook to GH pages
      - name: Deploying gh-actions-test to GH pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder the action should deploy.
